// svelte-ui/src/lib/components/ApplicationDetail.svelte
<script lang="ts">
  import type { Application, UpdateApplicationInput, CreateInterviewStageInput, UpdateInterviewStageInput, ApplicationStatus } from '$lib/types';
  import { ALL_STATUSES, STATUS_LABELS, CATEGORY_LABELS, SOURCE_LABELS } from '$lib/types';
  import StatusBadge from './StatusBadge.svelte';
  import RatingDisplay from './RatingDisplay.svelte';
  import InterviewStageList from './InterviewStageList.svelte';
  import ApplicationForm from './ApplicationForm.svelte';

  interface Props {
    application: Application;
    onUpdate: (input: UpdateApplicationInput) => Promise<void>;
    onAddStage: (input: CreateInterviewStageInput) => Promise<void>;
    onUpdateStage: (stageId: string, input: UpdateInterviewStageInput) => Promise<void>;
    onRemoveStage: (stageId: string) => Promise<void>;
    onArchive: () => Promise<void>;
    onDelete: () => Promise<void>;
    onClose: () => void;
  }

  let { application, onUpdate, onAddStage, onUpdateStage, onRemoveStage, onArchive, onDelete, onClose }: Props = $props();

  let isEditing = $state(false);
  let showDeleteConfirm = $state(false);

  function formatDate(dateStr: string): string {
    return new Date(dateStr).toLocaleDateString('en-US', {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });
  }

  function formatSalary(min: number | null, max: number | null): string | null {
    if (!min && !max) return null;
    const formatter = new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 });
    if (min && max) return `${formatter.format(min)} - ${formatter.format(max)}`;
    if (min) return `${formatter.format(min)}+`;
    return `Up to ${formatter.format(max!)}`;
  }

  async function handleStatusChange(e: Event) {
    const select = e.target as HTMLSelectElement;
    await onUpdate({ status: select.value as ApplicationStatus });
  }

  async function handleOfferDateChange(e: Event) {
    const input = e.target as HTMLInputElement;
    await onUpdate({ offerDueDate: input.value || null });
  }

  async function handleFormSubmit(input: UpdateApplicationInput) {
    await onUpdate(input);
    isEditing = false;
  }

  async function handleDelete() {
    await onDelete();
    showDeleteConfirm = false;
  }

  const salaryRange = $derived(formatSalary(application.salaryMin, application.salaryMax));
</script>

<div class="h-full flex flex-col">
  <!-- Header -->
  <div class="flex items-start justify-between p-6 border-b border-gray-200 dark:border-gray-700">
    <div class="flex-1 min-w-0">
      <div class="flex items-center gap-3 mb-2">
        <h2 class="text-2xl font-bold text-gray-900 dark:text-gray-100 truncate">
          {application.companyName}
        </h2>
        {#if application.isArchived}
          <span class="text-sm text-gray-500 dark:text-gray-400">(Archived)</span>
        {/if}
      </div>
      <p class="text-lg text-gray-600 dark:text-gray-400">{application.positionTitle}</p>
    </div>
    <button
      type="button"
      class="p-2 rounded-full hover:bg-gray-100 dark:hover:bg-gray-700"
      onclick={onClose}
      aria-label="Close"
    >
      <svg class="h-6 w-6 text-gray-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
      </svg>
    </button>
  </div>

  <!-- Content -->
  <div class="flex-1 overflow-y-auto p-6">
    {#if isEditing}
      <ApplicationForm
        {application}
        onsubmit={handleFormSubmit}
        oncancel={() => (isEditing = false)}
      />
    {:else}
      <div class="space-y-6">
        <!-- Status and Quick Actions -->
        <div class="flex flex-wrap items-center gap-4">
          <div class="flex items-center gap-2">
            <label for="status" class="text-sm font-medium text-gray-700 dark:text-gray-300">Status:</label>
            <select
              id="status"
              class="input w-auto"
              value={application.status}
              onchange={handleStatusChange}
            >
              {#each ALL_STATUSES as status}
                <option value={status}>{STATUS_LABELS[status]}</option>
              {/each}
            </select>
          </div>

          {#if application.status === 'given offer'}
            <div class="flex items-center gap-2">
              <label for="offerDate" class="text-sm font-medium text-gray-700 dark:text-gray-300">Offer Due:</label>
              <input
                id="offerDate"
                type="date"
                class="input w-auto"
                value={application.offerDueDate || ''}
                onchange={handleOfferDateChange}
              />
            </div>
          {/if}
        </div>

        <!-- Details Grid -->
        <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div class="space-y-4">
            <div>
              <h4 class="text-sm font-medium text-gray-500 dark:text-gray-400 mb-1">Date Applied</h4>
              <p class="text-gray-900 dark:text-gray-100">{formatDate(application.dateApplied)}</p>
            </div>

            {#if application.companyCategory}
              <div>
                <h4 class="text-sm font-medium text-gray-500 dark:text-gray-400 mb-1">Industry</h4>
                <p class="text-gray-900 dark:text-gray-100">{CATEGORY_LABELS[application.companyCategory]}</p>
              </div>
            {/if}

            {#if application.jobSource}
              <div>
                <h4 class="text-sm font-medium text-gray-500 dark:text-gray-400 mb-1">Job Source</h4>
                <p class="text-gray-900 dark:text-gray-100">{SOURCE_LABELS[application.jobSource]}</p>
              </div>
            {/if}

            {#if application.skillsMatch}
              <div>
                <h4 class="text-sm font-medium text-gray-500 dark:text-gray-400 mb-1">Skills Match</h4>
                <RatingDisplay value={application.skillsMatch} />
              </div>
            {/if}
          </div>

          <div class="space-y-4">
            {#if salaryRange}
              <div>
                <h4 class="text-sm font-medium text-gray-500 dark:text-gray-400 mb-1">Salary Range</h4>
                <p class="text-gray-900 dark:text-gray-100">{salaryRange}</p>
              </div>
            {/if}

            {#if application.coverLetterRequired !== null}
              <div>
                <h4 class="text-sm font-medium text-gray-500 dark:text-gray-400 mb-1">Cover Letter</h4>
                <p class="text-gray-900 dark:text-gray-100">{application.coverLetterRequired ? 'Required' : 'Not Required'}</p>
              </div>
            {/if}

            {#if application.specialRequirements}
              <div>
                <h4 class="text-sm font-medium text-gray-500 dark:text-gray-400 mb-1">Special Requirements</h4>
                <p class="text-gray-900 dark:text-gray-100">{application.specialRequirements}</p>
              </div>
            {/if}
          </div>
        </div>

        <!-- Links -->
        {#if application.companyUrl || application.jobPostingUrl || application.companyCareerUrl}
          <div>
            <h4 class="text-sm font-medium text-gray-500 dark:text-gray-400 mb-2">Links</h4>
            <div class="flex flex-wrap gap-3">
              {#if application.companyUrl}
                <a
                  href={application.companyUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  class="text-primary-600 hover:text-primary-700 dark:text-primary-400 text-sm"
                >
                  Company Website
                </a>
              {/if}
              {#if application.jobPostingUrl}
                <a
                  href={application.jobPostingUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  class="text-primary-600 hover:text-primary-700 dark:text-primary-400 text-sm"
                >
                  Job Posting
                </a>
              {/if}
              {#if application.companyCareerUrl}
                <a
                  href={application.companyCareerUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  class="text-primary-600 hover:text-primary-700 dark:text-primary-400 text-sm"
                >
                  Careers Page
                </a>
              {/if}
            </div>
          </div>
        {/if}

        <!-- Notes -->
        {#if application.notes}
          <div>
            <h4 class="text-sm font-medium text-gray-500 dark:text-gray-400 mb-2">Notes</h4>
            <p class="text-gray-900 dark:text-gray-100 whitespace-pre-wrap">{application.notes}</p>
          </div>
        {/if}

        <!-- Interview Stages -->
        <div class="pt-4 border-t border-gray-200 dark:border-gray-700">
          <InterviewStageList
            stages={application.interviewStages}
            onAdd={onAddStage}
            onUpdate={onUpdateStage}
            onRemove={onRemoveStage}
          />
        </div>
      </div>
    {/if}
  </div>

  <!-- Footer Actions -->
  {#if !isEditing}
    <div class="flex items-center justify-between p-4 border-t border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-800/50">
      <div class="flex gap-2">
        <button type="button" class="btn-secondary" onclick={() => (isEditing = true)}>
          Edit
        </button>
        <button type="button" class="btn-secondary" onclick={onArchive}>
          {application.isArchived ? 'Restore' : 'Archive'}
        </button>
      </div>
      <div>
        {#if showDeleteConfirm}
          <div class="flex items-center gap-2">
            <span class="text-sm text-gray-600 dark:text-gray-400">Are you sure?</span>
            <button type="button" class="btn-danger" onclick={handleDelete}>Delete</button>
            <button type="button" class="btn-secondary" onclick={() => (showDeleteConfirm = false)}>Cancel</button>
          </div>
        {:else}
          <button type="button" class="btn-danger" onclick={() => (showDeleteConfirm = true)}>
            Delete
          </button>
        {/if}
      </div>
    </div>
  {/if}
</div>

// ui/src/components/applications/ApplicationDetail.tsx
'use client';

import { useState } from 'react';
import type {
  JobApplication,
  InterviewStage,
  UpdateApplicationInput,
  UpdateInterviewStageInput,
} from '@/types/application';
import { InterviewChecklist } from '@/components/interviews/InterviewChecklist';
import { Button } from '@/components/ui/Button';
import { Input } from '@/components/ui/Input';
import { StatusBadge } from '@/components/ui/Badge';
import { Select, type SelectOption } from '@/components/ui/Select';
import { formatDate, formatSalaryRange, getDaysRemaining, formatDaysRemaining, cn } from '@/lib/utils';
import {
  APPLICATION_STATUSES,
  STATUS_LABELS,
  CATEGORY_LABELS,
  SOURCE_LABELS,
  SKILLS_MATCH_LABELS,
} from '@/lib/constants';
import { EditIcon } from '@/assets/icons/EditIcon';
import { CalendarIcon } from '@/assets/icons/CalendarIcon';

export interface ApplicationDetailProps {
  application: JobApplication;
  onUpdate: (id: string, data: UpdateApplicationInput) => void;
  onAddStage: (stage: InterviewStage) => Promise<void>;
  onUpdateStage: (stageId: string, stage: UpdateInterviewStageInput) => Promise<void>;
  onRemoveStage: (stageId: string) => Promise<void>;
  onEdit: () => void;
  onClose: () => void;
}

const statusOptions: SelectOption[] = APPLICATION_STATUSES.map((status) => ({
  value: status,
  label: STATUS_LABELS[status],
}));

function DetailRow({
  label,
  value,
  isLink = false,
}: {
  label: string;
  value: React.ReactNode;
  isLink?: boolean;
}): React.ReactElement | null {
  if (!value) return null;

  return (
    <div className="py-2 flex justify-between items-start gap-4">
      <dt className="text-sm font-medium text-gray-500 dark:text-slate-400 flex-shrink-0">{label}</dt>
      <dd className="text-sm text-gray-900 dark:text-slate-100 text-right">
        {isLink && typeof value === 'string' ? (
          <a
            href={value}
            target="_blank"
            rel="noopener noreferrer"
            className="text-blue-600 dark:text-blue-400 hover:text-blue-800 dark:hover:text-blue-300 hover:underline break-all"
          >
            {value}
          </a>
        ) : (
          value
        )}
      </dd>
    </div>
  );
}

export function ApplicationDetail({
  application,
  onUpdate,
  onAddStage,
  onUpdateStage,
  onRemoveStage,
  onEdit,
  onClose,
}: ApplicationDetailProps): React.ReactElement {
  const [isStatusChanging, setIsStatusChanging] = useState(false);
  const [isEditingDueDate, setIsEditingDueDate] = useState(false);
  const [dueDateValue, setDueDateValue] = useState(application.offerDueDate ?? '');

  const handleStatusChange = (e: React.ChangeEvent<HTMLSelectElement>): void => {
    const newStatus = e.target.value as JobApplication['status'];
    onUpdate(application.id, { status: newStatus });
    setIsStatusChanging(false);
  };

  const handleDueDateSave = (): void => {
    onUpdate(application.id, { offerDueDate: dueDateValue || undefined });
    setIsEditingDueDate(false);
  };

  const handleDueDateCancel = (): void => {
    setDueDateValue(application.offerDueDate ?? '');
    setIsEditingDueDate(false);
  };

  const salaryRange = formatSalaryRange(application.salaryMin, application.salaryMax);
  const showInterviewSection =
    application.status === 'interviewing' ||
    application.status === 'given offer' ||
    application.status === 'accepted offer' ||
    application.interviewStages.length > 0;

  const isOffered = application.status === 'given offer';
  const daysRemaining = application.offerDueDate ? getDaysRemaining(application.offerDueDate) : null;

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-start justify-between gap-4">
        <div className="flex-1">
          <h2 className="text-xl font-semibold text-gray-900 dark:text-slate-50">{application.positionTitle}</h2>
          <p className="text-lg text-gray-600 dark:text-slate-300">{application.companyName}</p>
        </div>
        <div className="flex items-center gap-2">
          {isStatusChanging ? (
            <Select
              value={application.status}
              onChange={handleStatusChange}
              options={statusOptions}
              className="w-36"
              aria-label="Change application status"
            />
          ) : (
            <button
              type="button"
              onClick={() => setIsStatusChanging(true)}
              className="focus:outline-none focus:ring-2 focus:ring-blue-500 rounded"
              aria-label="Click to change status"
            >
              <StatusBadge status={application.status} size="md" />
            </button>
          )}
          <Button variant="ghost" size="sm" onClick={onEdit} aria-label="Edit application">
            <EditIcon className="w-4 h-4" />
          </Button>
        </div>
      </div>

      {/* Details Section */}
      <div className="bg-gray-50 dark:bg-slate-700 rounded-lg p-4 sticky top-0 z-10">
        <h3 className="text-sm font-semibold text-gray-900 dark:text-slate-50 mb-3">Application Details</h3>
        <dl className="divide-y divide-gray-200 dark:divide-slate-600">
          <DetailRow label="Date Applied" value={formatDate(application.dateApplied)} />
          <DetailRow
            label="Category"
            value={
              application.companyCategory
                ? CATEGORY_LABELS[application.companyCategory]
                : undefined
            }
          />
          <DetailRow
            label="Source"
            value={application.jobSource ? SOURCE_LABELS[application.jobSource] : undefined}
          />
          <DetailRow
            label="Skills Match"
            value={
              application.skillsMatch
                ? SKILLS_MATCH_LABELS[application.skillsMatch]
                : undefined
            }
          />
          <DetailRow label="Salary Range" value={salaryRange} />
          <DetailRow
            label="Cover Letter"
            value={application.coverLetterRequired ? 'Required' : undefined}
          />
        </dl>
      </div>

      {/* URLs Section */}
      {(application.companyUrl || application.jobPostingUrl || application.companyCareerUrl) && (
        <div className="bg-gray-50 dark:bg-slate-700 rounded-lg p-4">
          <h3 className="text-sm font-semibold text-gray-900 dark:text-slate-50 mb-3">Links</h3>
          <dl className="divide-y divide-gray-200 dark:divide-slate-600">
            <DetailRow label="Company Website" value={application.companyUrl} isLink />
            <DetailRow label="Job Posting" value={application.jobPostingUrl} isLink />
            <DetailRow label="Career Page" value={application.companyCareerUrl} isLink />
          </dl>
        </div>
      )}

      {/* Notes Section */}
      {(application.specialRequirements || application.notes) && (
        <div className="bg-gray-50 dark:bg-slate-700 rounded-lg p-4">
          <h3 className="text-sm font-semibold text-gray-900 dark:text-slate-50 mb-3">Notes</h3>
          {application.specialRequirements && (
            <div className="mb-3">
              <p className="text-xs font-medium text-gray-500 dark:text-slate-400 mb-1">Special Requirements</p>
              <p className="text-sm text-gray-900 dark:text-slate-100 whitespace-pre-wrap">
                {application.specialRequirements}
              </p>
            </div>
          )}
          {application.notes && (
            <div>
              <p className="text-xs font-medium text-gray-500 dark:text-slate-400 mb-1">General Notes</p>
              <p className="text-sm text-gray-900 dark:text-slate-100 whitespace-pre-wrap">{application.notes}</p>
            </div>
          )}
        </div>
      )}

      {/* Offer Due Date Section */}
      {isOffered && (
        <div className="bg-amber-50 dark:bg-amber-900/20 border border-amber-200 dark:border-amber-800 rounded-lg p-4">
          <div className="flex items-center justify-between gap-4">
            <div className="flex items-center gap-2">
              <CalendarIcon className="w-5 h-5 text-amber-600 dark:text-amber-500" />
              <h3 className="text-sm font-semibold text-amber-900 dark:text-amber-300">Offer Decision Deadline</h3>
            </div>
            {!isEditingDueDate && (
              <Button
                variant="ghost"
                size="sm"
                onClick={() => setIsEditingDueDate(true)}
              >
                {application.offerDueDate ? 'Edit' : 'Set Deadline'}
              </Button>
            )}
          </div>

          {isEditingDueDate ? (
            <div className="mt-3 flex items-end gap-2">
              <div className="flex-1">
                <Input
                  label="Due Date"
                  type="date"
                  value={dueDateValue}
                  onChange={(e) => setDueDateValue(e.target.value)}
                />
              </div>
              <Button size="sm" onClick={handleDueDateSave}>
                Save
              </Button>
              <Button variant="secondary" size="sm" onClick={handleDueDateCancel}>
                Cancel
              </Button>
            </div>
          ) : application.offerDueDate ? (
            <div className="mt-2">
              <p className="text-sm text-amber-800 dark:text-amber-200">
                <span className="font-medium">Due: </span>
                {formatDate(application.offerDueDate)}
              </p>
              {daysRemaining !== null && (
                <p
                  className={cn(
                    'text-sm font-medium mt-1',
                    daysRemaining < 0
                      ? 'text-red-600 dark:text-red-400'
                      : daysRemaining <= 3
                        ? 'text-amber-600 dark:text-amber-400'
                        : 'text-green-600 dark:text-green-400'
                  )}
                >
                  {formatDaysRemaining(daysRemaining)}
                </p>
              )}
            </div>
          ) : (
            <p className="mt-2 text-sm text-amber-700 dark:text-amber-300">
              No deadline set. Click &quot;Set Deadline&quot; to add one.
            </p>
          )}
        </div>
      )}

      {/* Interview Progress Section */}
      {showInterviewSection && (
        <div className="border-t border-gray-200 dark:border-slate-700 pt-6">
          <InterviewChecklist
            stages={application.interviewStages}
            onAddStage={onAddStage}
            onUpdateStage={onUpdateStage}
            onRemoveStage={onRemoveStage}
            isEditable={application.status === 'interviewing'}
          />
        </div>
      )}

      {/* Metadata */}
      <div className="text-xs text-gray-400 border-t pt-4">
        <p>Created: {formatDate(application.createdAt)}</p>
        <p>Last updated: {formatDate(application.updatedAt)}</p>
        {application.isArchived && (
          <p className={cn('mt-1 font-medium text-amber-600')}>This application is archived</p>
        )}
      </div>

      {/* Footer Actions */}
      <div className="flex justify-end gap-3 pt-4 border-t">
        <Button variant="secondary" onClick={onClose}>
          Close
        </Button>
        <Button onClick={onEdit}>Edit Application</Button>
      </div>
    </div>
  );
}
