// react-ui/src/components/applications/ApplicationCard.tsx
import { useState } from "react";
import type { Application } from "../../types/application";
import { Card, Badge, RatingDisplay, ConfirmDialog } from "../ui";
import { formatDate, getDaysUntil, isOverdue } from "../../lib/utils";
import { COMPANY_CATEGORIES } from "../../lib/constants";
import { cn } from "../../lib/utils";

interface ApplicationCardProps {
  application: Application;
  onClick: () => void;
  onArchive: () => void;
  onDelete: () => void;
}

export function ApplicationCard({
  application,
  onClick,
  onArchive,
  onDelete,
}: ApplicationCardProps) {
  const [showMenu, setShowMenu] = useState(false);
  const [showDeleteConfirm, setShowDeleteConfirm] = useState(false);

  const categoryLabel = application.companyCategory
    ? COMPANY_CATEGORIES.find((c) => c.value === application.companyCategory)
        ?.label
    : null;

  const completedStages = application.interviewStages.filter(
    (s) => s.isCompleted
  ).length;
  const totalStages = application.interviewStages.length;

  const daysUntil = getDaysUntil(application.offerDueDate);
  const offerOverdue = isOverdue(application.offerDueDate);

  return (
    <>
      <Card
        hoverable
        className={cn(
          "relative",
          application.isArchived && "opacity-60"
        )}
      >
        <div className="p-4" onClick={onClick}>
          <div className="flex items-start justify-between mb-2">
            <div className="flex-1 min-w-0">
              <h3 className="text-lg font-semibold text-gray-900 dark:text-white truncate">
                {application.companyName}
              </h3>
              <p className="text-sm text-gray-600 dark:text-gray-400 truncate">
                {application.positionTitle}
              </p>
            </div>
            <div className="ml-4 flex-shrink-0">
              <Badge status={application.status} />
            </div>
          </div>

          <div className="flex flex-wrap items-center gap-x-4 gap-y-2 mt-3 text-sm text-gray-500 dark:text-gray-400">
            <span>Applied: {formatDate(application.dateApplied)}</span>

            {categoryLabel && <span>{categoryLabel}</span>}

            {application.skillsMatch && (
              <RatingDisplay value={application.skillsMatch} size="sm" />
            )}

            {application.status === "interviewing" && totalStages > 0 && (
              <span className="text-purple-600 dark:text-purple-400">
                {completedStages}/{totalStages} stages
              </span>
            )}

            {application.status === "given offer" &&
              application.offerDueDate && (
                <span
                  className={cn(
                    "font-medium",
                    offerOverdue
                      ? "text-red-600 dark:text-red-400"
                      : daysUntil !== null && daysUntil <= 3
                      ? "text-yellow-600 dark:text-yellow-400"
                      : "text-green-600 dark:text-green-400"
                  )}
                >
                  {offerOverdue
                    ? "Overdue!"
                    : daysUntil === 0
                    ? "Due today"
                    : `${daysUntil} days left`}
                </span>
              )}

            {application.isArchived && (
              <span className="text-gray-400 dark:text-gray-500 italic">
                Archived
              </span>
            )}
          </div>
        </div>

        {/* Actions Menu */}
        <div
          className="absolute top-4 right-4"
          onClick={(e) => e.stopPropagation()}
        >
          <button
            onClick={() => setShowMenu(!showMenu)}
            className="p-1 text-gray-400 hover:text-gray-600 dark:hover:text-gray-300 rounded-full hover:bg-gray-100 dark:hover:bg-gray-700"
            aria-label="Actions"
          >
            <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
              <path d="M10 6a2 2 0 110-4 2 2 0 010 4zM10 12a2 2 0 110-4 2 2 0 010 4zM10 18a2 2 0 110-4 2 2 0 010 4z" />
            </svg>
          </button>

          {showMenu && (
            <>
              <div
                className="fixed inset-0 z-10"
                onClick={() => setShowMenu(false)}
              />
              <div className="absolute right-0 mt-1 z-20 w-36 bg-white dark:bg-gray-800 rounded-lg shadow-lg border border-gray-200 dark:border-gray-700 py-1">
                <button
                  onClick={() => {
                    setShowMenu(false);
                    onArchive();
                  }}
                  className="w-full px-4 py-2 text-left text-sm text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700"
                >
                  {application.isArchived ? "Restore" : "Archive"}
                </button>
                <button
                  onClick={() => {
                    setShowMenu(false);
                    setShowDeleteConfirm(true);
                  }}
                  className="w-full px-4 py-2 text-left text-sm text-red-600 dark:text-red-400 hover:bg-gray-100 dark:hover:bg-gray-700"
                >
                  Delete
                </button>
              </div>
            </>
          )}
        </div>
      </Card>

      <ConfirmDialog
        isOpen={showDeleteConfirm}
        onClose={() => setShowDeleteConfirm(false)}
        onConfirm={() => {
          setShowDeleteConfirm(false);
          onDelete();
        }}
        title="Delete Application"
        message={`Are you sure you want to delete the application for ${application.positionTitle} at ${application.companyName}? This action cannot be undone.`}
        confirmLabel="Delete"
        isDestructive
      />
    </>
  );
}

// svelte-ui/src/lib/components/ApplicationCard.svelte
<script lang="ts">
  import type { Application } from '$lib/types';
  import { CATEGORY_LABELS } from '$lib/types';
  import StatusBadge from './StatusBadge.svelte';
  import RatingDisplay from './RatingDisplay.svelte';

  interface Props {
    application: Application;
    onclick: () => void;
    onarchive: () => void;
    ondelete: () => void;
  }

  let { application, onclick, onarchive, ondelete }: Props = $props();

  let menuOpen = $state(false);

  const completedStages = $derived(application.interviewStages.filter((s) => s.isCompleted).length);
  const totalStages = $derived(application.interviewStages.length);

  const daysUntilDue = $derived(() => {
    if (!application.offerDueDate) return null;
    const due = new Date(application.offerDueDate);
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    const diffTime = due.getTime() - today.getTime();
    return Math.ceil(diffTime / (1000 * 60 * 60 * 24));
  });

  function formatDate(dateStr: string): string {
    return new Date(dateStr).toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
      year: 'numeric',
    });
  }

  function handleMenuClick(e: MouseEvent) {
    e.stopPropagation();
    menuOpen = !menuOpen;
  }

  function handleArchiveClick(e: MouseEvent) {
    e.stopPropagation();
    menuOpen = false;
    onarchive();
  }

  function handleDeleteClick(e: MouseEvent) {
    e.stopPropagation();
    menuOpen = false;
    ondelete();
  }
</script>

<div
  class="card p-4 hover:shadow-md transition-shadow cursor-pointer {application.isArchived ? 'opacity-60' : ''}"
  onclick={onclick}
  onkeydown={(e) => e.key === 'Enter' && onclick()}
  tabindex="0"
  role="button"
>
  <div class="flex items-start justify-between gap-4">
    <div class="flex-1 min-w-0">
      <div class="flex items-center gap-2 mb-1">
        <h3 class="text-lg font-semibold text-gray-900 dark:text-gray-100 truncate">
          {application.companyName}
        </h3>
        {#if application.isArchived}
          <span class="text-xs text-gray-500 dark:text-gray-400">(Archived)</span>
        {/if}
      </div>
      <p class="text-gray-600 dark:text-gray-400 truncate">{application.positionTitle}</p>
    </div>
    <div class="flex items-center gap-2">
      <StatusBadge status={application.status} />
      <div class="relative">
        <button
          type="button"
          class="p-1 rounded-full hover:bg-gray-100 dark:hover:bg-gray-700"
          onclick={handleMenuClick}
          aria-label="Actions"
        >
          <svg class="h-5 w-5 text-gray-500" fill="currentColor" viewBox="0 0 20 20">
            <path
              d="M10 6a2 2 0 110-4 2 2 0 010 4zM10 12a2 2 0 110-4 2 2 0 010 4zM10 18a2 2 0 110-4 2 2 0 010 4z"
            />
          </svg>
        </button>
        {#if menuOpen}
          <div
            class="absolute right-0 mt-1 w-36 bg-white dark:bg-gray-800 rounded-md shadow-lg border border-gray-200 dark:border-gray-700 z-10"
          >
            <button
              type="button"
              class="w-full px-4 py-2 text-left text-sm text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700"
              onclick={handleArchiveClick}
            >
              {application.isArchived ? 'Restore' : 'Archive'}
            </button>
            <button
              type="button"
              class="w-full px-4 py-2 text-left text-sm text-red-600 dark:text-red-400 hover:bg-gray-100 dark:hover:bg-gray-700"
              onclick={handleDeleteClick}
            >
              Delete
            </button>
          </div>
        {/if}
      </div>
    </div>
  </div>

  <div class="mt-3 flex flex-wrap items-center gap-x-4 gap-y-2 text-sm text-gray-500 dark:text-gray-400">
    <span>Applied: {formatDate(application.dateApplied)}</span>
    {#if application.companyCategory}
      <span class="px-2 py-0.5 bg-gray-100 dark:bg-gray-700 rounded text-xs">
        {CATEGORY_LABELS[application.companyCategory]}
      </span>
    {/if}
    {#if application.skillsMatch}
      <RatingDisplay value={application.skillsMatch} />
    {/if}
    {#if application.status === 'interviewing' && totalStages > 0}
      <span>{completedStages}/{totalStages} stages</span>
    {/if}
    {#if application.status === 'given offer' && application.offerDueDate}
      {@const days = daysUntilDue()}
      {#if days !== null}
        <span class={days < 0 ? 'text-red-600 dark:text-red-400 font-medium' : days <= 3 ? 'text-yellow-600 dark:text-yellow-400' : ''}>
          {days < 0 ? 'Overdue' : `Due: ${formatDate(application.offerDueDate)}`}
        </span>
      {/if}
    {/if}
  </div>
</div>
