// angular-ui/src/app/shared/components/confirm-dialog/confirm-dialog.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';

@Component({
  selector: 'app-confirm-dialog',
  standalone: true,
  template: `
    <div class="fixed inset-0 bg-black/50 z-50 flex items-center justify-center">
      <div role="dialog" class="bg-white rounded-lg p-6 max-w-md w-full mx-4 shadow-xl dark:bg-gray-800">
        <h3 class="text-lg font-semibold text-gray-900 mb-2 dark:text-white">{{ title }}</h3>
        <p class="text-gray-600 mb-4 dark:text-gray-300">{{ message }}</p>
        <div class="flex justify-end gap-3">
          <button
            type="button"
            (click)="cancelled.emit()"
            class="px-4 py-2 bg-white hover:bg-gray-50 text-gray-700 text-sm rounded border border-gray-300 dark:bg-gray-700 dark:hover:bg-gray-600 dark:text-gray-300 dark:border-gray-600"
          >
            Cancel
          </button>
          <button
            type="button"
            (click)="confirmed.emit()"
            [class]="confirmDanger
              ? 'px-4 py-2 bg-red-600 hover:bg-red-700 text-white text-sm rounded'
              : 'px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white text-sm rounded'"
          >
            {{ confirmLabel }}
          </button>
        </div>
      </div>
    </div>
  `,
})
export class ConfirmDialogComponent {
  @Input() title: string = 'Confirm';
  @Input() message: string = '';
  @Input() confirmLabel: string = 'Confirm';
  @Input() confirmDanger: boolean = false;
  @Output() confirmed = new EventEmitter<void>();
  @Output() cancelled = new EventEmitter<void>();
}

// svelte-ui/src/lib/components/ConfirmDialog.svelte
<script lang="ts">
  interface Props {
    title: string;
    message: string;
    confirmLabel?: string;
    cancelLabel?: string;
    confirmVariant?: 'primary' | 'danger';
    onconfirm: () => void;
    oncancel: () => void;
  }

  let {
    title,
    message,
    confirmLabel = 'Confirm',
    cancelLabel = 'Cancel',
    confirmVariant = 'primary',
    onconfirm,
    oncancel,
  }: Props = $props();

  function handleKeydown(e: KeyboardEvent) {
    if (e.key === 'Escape') {
      oncancel();
    }
  }

  function handleBackdropClick(e: MouseEvent) {
    const target = e.target as HTMLElement;
    if (target.classList.contains('dialog-backdrop')) {
      oncancel();
    }
  }
</script>

<div
  class="fixed inset-0 z-50 flex items-center justify-center dialog-backdrop bg-black/50"
  onkeydown={handleKeydown}
  onclick={handleBackdropClick}
  role="dialog"
  aria-modal="true"
  tabindex="-1"
>
  <div class="bg-white dark:bg-gray-800 rounded-lg shadow-xl p-6 max-w-md w-full mx-4">
    <h2 class="text-lg font-semibold text-gray-900 dark:text-gray-100 mb-2">{title}</h2>
    <p class="text-gray-600 dark:text-gray-400 mb-6">{message}</p>
    <div class="flex justify-end gap-3">
      <button type="button" class="btn-secondary" onclick={oncancel}>
        {cancelLabel}
      </button>
      <button type="button" class={confirmVariant === 'danger' ? 'btn-danger' : 'btn-primary'} onclick={onconfirm}>
        {confirmLabel}
      </button>
    </div>
  </div>
</div>
