// lambda-react-ui/src/components/ui/ConfirmDialog.tsx
import { Button } from './Button';
import { Modal } from './Modal';

interface ConfirmDialogProps {
  open: boolean;
  title: string;
  message: string;
  confirmLabel?: string;
  cancelLabel?: string;
  variant?: 'default' | 'danger';
  onConfirm: () => void;
  onCancel: () => void;
}

export function ConfirmDialog({
  open,
  title,
  message,
  confirmLabel = 'Confirm',
  cancelLabel = 'Cancel',
  variant = 'default',
  onConfirm,
  onCancel,
}: ConfirmDialogProps) {
  return (
    <Modal open={open} onClose={onCancel}>
      <div
        className="w-full max-w-md rounded-lg border border-[var(--border-subtle)] bg-[var(--bg-elevated)] p-4"
        data-testid="confirm-dialog"
        role="dialog"
        aria-modal="true"
        aria-label={title}
      >
        <h2 className="m-0 text-lg font-semibold text-[var(--text-primary)]">{title}</h2>
        <p className="mt-2 text-sm text-[var(--text-secondary)]">{message}</p>
        <div className="mt-4 flex justify-end gap-2">
          <Button variant="secondary" onClick={onCancel} type="button">
            {cancelLabel}
          </Button>
          <Button variant={variant === 'danger' ? 'danger' : 'primary'} onClick={onConfirm} type="button">
            {confirmLabel}
          </Button>
        </div>
      </div>
    </Modal>
  );
}

// svelte-ui/src/lib/components/ConfirmDialog.svelte
<script lang="ts">
  interface Props {
    title: string;
    message: string;
    confirmLabel?: string;
    cancelLabel?: string;
    confirmVariant?: 'primary' | 'danger';
    onconfirm: () => void;
    oncancel: () => void;
  }

  let {
    title,
    message,
    confirmLabel = 'Confirm',
    cancelLabel = 'Cancel',
    confirmVariant = 'primary',
    onconfirm,
    oncancel,
  }: Props = $props();

  function handleKeydown(e: KeyboardEvent) {
    if (e.key === 'Escape') {
      oncancel();
    }
  }

  function handleBackdropClick(e: MouseEvent) {
    const target = e.target as HTMLElement;
    if (target.classList.contains('dialog-backdrop')) {
      oncancel();
    }
  }
</script>

<div
  class="fixed inset-0 z-50 flex items-center justify-center dialog-backdrop bg-black/50"
  onkeydown={handleKeydown}
  onclick={handleBackdropClick}
  role="dialog"
  aria-modal="true"
  tabindex="-1"
>
  <div class="bg-white dark:bg-gray-800 rounded-lg shadow-xl p-6 max-w-md w-full mx-4">
    <h2 class="text-lg font-semibold text-gray-900 dark:text-gray-100 mb-2">{title}</h2>
    <p class="text-gray-600 dark:text-gray-400 mb-6">{message}</p>
    <div class="flex justify-end gap-3">
      <button type="button" class="btn-secondary" onclick={oncancel}>
        {cancelLabel}
      </button>
      <button type="button" class={confirmVariant === 'danger' ? 'btn-danger' : 'btn-primary'} onclick={onconfirm}>
        {confirmLabel}
      </button>
    </div>
  </div>
</div>
