// react-apollo-ui/src/components/applications/FilterBar.tsx
import type { ApplicationStatus, CompanyCategory, JobSource } from '../../types/application.js';
import { STATUS_LABELS, CATEGORY_LABELS, SOURCE_LABELS, COMPANY_CATEGORIES, JOB_SOURCES } from '../../types/application.js';

export interface Filters {
  status?: ApplicationStatus;
  companyCategory?: CompanyCategory;
  jobSource?: JobSource;
  skillsMatchMin?: number;
  includeArchived?: boolean;
  sortBy?: string;
  sortDir?: string;
}

interface FilterBarProps {
  filters: Filters;
  onFilterChange: (filters: Filters) => void;
}

const STATUS_OPTIONS: { value: ApplicationStatus; label: string }[] = [
  { value: 'unsubmitted', label: STATUS_LABELS.unsubmitted },
  { value: 'applied', label: STATUS_LABELS.applied },
  { value: 'interviewing', label: STATUS_LABELS.interviewing },
  { value: 'given offer', label: STATUS_LABELS['given offer'] },
  { value: 'accepted offer', label: STATUS_LABELS['accepted offer'] },
  { value: 'declined offer', label: STATUS_LABELS['declined offer'] },
  { value: 'rejected', label: STATUS_LABELS.rejected },
  { value: 'no offer', label: STATUS_LABELS['no offer'] },
];

const CATEGORY_OPTIONS = COMPANY_CATEGORIES.map((v) => ({ value: v, label: CATEGORY_LABELS[v] }));
const SOURCE_OPTIONS = JOB_SOURCES.map((v) => ({ value: v, label: SOURCE_LABELS[v] }));

const SORT_OPTIONS = [
  { value: 'updatedAt', label: 'Last Updated' },
  { value: 'dateApplied', label: 'Date Applied' },
  { value: 'companyName', label: 'Company Name' },
  { value: 'skillsMatch', label: 'Skills Match' },
];

export function FilterBar({ filters, onFilterChange }: FilterBarProps) {
  const update = (partial: Partial<Filters>) => onFilterChange({ ...filters, ...partial });

  return (
    <div className="bg-white dark:bg-gray-800 rounded-lg border border-gray-200 dark:border-gray-700 p-4">
      <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-3">
        <div>
          <label htmlFor="filter-status" className="block text-xs font-medium text-gray-600 dark:text-gray-400 mb-1">Status</label>
          <select
            id="filter-status"
            value={filters.status ?? ''}
            onChange={(e) => update({ status: (e.target.value || undefined) as ApplicationStatus | undefined })}
            className="w-full px-2 py-1.5 text-sm border border-gray-300 dark:border-gray-600 rounded bg-white dark:bg-gray-700 dark:text-white focus:outline-none focus:ring-1 focus:ring-blue-500"
          >
            <option value="">All statuses</option>
            {STATUS_OPTIONS.map((o) => <option key={o.value} value={o.value}>{o.label}</option>)}
          </select>
        </div>

        <div>
          <label htmlFor="filter-category" className="block text-xs font-medium text-gray-600 dark:text-gray-400 mb-1">Category</label>
          <select
            id="filter-category"
            value={filters.companyCategory ?? ''}
            onChange={(e) => update({ companyCategory: (e.target.value || undefined) as CompanyCategory | undefined })}
            className="w-full px-2 py-1.5 text-sm border border-gray-300 dark:border-gray-600 rounded bg-white dark:bg-gray-700 dark:text-white focus:outline-none focus:ring-1 focus:ring-blue-500"
          >
            <option value="">All categories</option>
            {CATEGORY_OPTIONS.map((o) => <option key={o.value} value={o.value}>{o.label}</option>)}
          </select>
        </div>

        <div>
          <label htmlFor="filter-source" className="block text-xs font-medium text-gray-600 dark:text-gray-400 mb-1">Source</label>
          <select
            id="filter-source"
            value={filters.jobSource ?? ''}
            onChange={(e) => update({ jobSource: (e.target.value || undefined) as JobSource | undefined })}
            className="w-full px-2 py-1.5 text-sm border border-gray-300 dark:border-gray-600 rounded bg-white dark:bg-gray-700 dark:text-white focus:outline-none focus:ring-1 focus:ring-blue-500"
          >
            <option value="">All sources</option>
            {SOURCE_OPTIONS.map((o) => <option key={o.value} value={o.value}>{o.label}</option>)}
          </select>
        </div>

        <div>
          <label htmlFor="filter-skills" className="block text-xs font-medium text-gray-600 dark:text-gray-400 mb-1">Skills Match Min</label>
          <input
            id="filter-skills"
            type="number"
            min="1"
            max="5"
            value={filters.skillsMatchMin ?? ''}
            onChange={(e) => update({ skillsMatchMin: e.target.value ? Number(e.target.value) : undefined })}
            className="w-full px-2 py-1.5 text-sm border border-gray-300 dark:border-gray-600 rounded bg-white dark:bg-gray-700 dark:text-white focus:outline-none focus:ring-1 focus:ring-blue-500"
            placeholder="1-5"
          />
        </div>

        <div>
          <label htmlFor="filter-sort" className="block text-xs font-medium text-gray-600 dark:text-gray-400 mb-1">Sort By</label>
          <select
            id="filter-sort"
            value={filters.sortBy ?? 'updatedAt'}
            onChange={(e) => update({ sortBy: e.target.value })}
            className="w-full px-2 py-1.5 text-sm border border-gray-300 dark:border-gray-600 rounded bg-white dark:bg-gray-700 dark:text-white focus:outline-none focus:ring-1 focus:ring-blue-500"
          >
            {SORT_OPTIONS.map((o) => <option key={o.value} value={o.value}>{o.label}</option>)}
          </select>
        </div>

        <div className="flex flex-col gap-2">
          <label className="flex items-center gap-2 text-xs font-medium text-gray-600 dark:text-gray-400 mt-5">
            <input
              id="filter-archived"
              type="checkbox"
              checked={filters.includeArchived ?? false}
              onChange={(e) => update({ includeArchived: e.target.checked })}
              className="w-3.5 h-3.5"
            />
            Include Archived
          </label>
          <button
            type="button"
            onClick={() => update({ sortDir: filters.sortDir === 'asc' ? 'desc' : 'asc' })}
            className="px-2 py-1 text-xs border border-gray-300 dark:border-gray-600 rounded bg-white dark:bg-gray-700 dark:text-white hover:bg-gray-50 dark:hover:bg-gray-600"
          >
            {filters.sortDir === 'asc' ? 'Asc' : 'Desc'}
          </button>
        </div>
      </div>
    </div>
  );
}

// svelte-ui/src/lib/components/FilterBar.svelte
<script lang="ts">
  import type { FilterState, CompanyCategory, JobSource } from '$lib/types';
  import { ALL_STATUSES, ALL_CATEGORIES, ALL_SOURCES, STATUS_LABELS, CATEGORY_LABELS, SOURCE_LABELS } from '$lib/types';

  interface Props {
    filters: FilterState;
    resultCount: number;
    totalCount: number;
    onchange: (filters: Partial<FilterState>) => void;
    onreset: () => void;
  }

  let { filters, resultCount, totalCount, onchange, onreset }: Props = $props();

  const hasActiveFilters = $derived(
    filters.status || filters.companyCategory || filters.jobSource || filters.skillsMatchMin || filters.includeArchived
  );
</script>

<div class="bg-white dark:bg-gray-800 p-4 rounded-lg shadow-xs border border-gray-200 dark:border-gray-700">
  <div class="grid gap-4 grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 items-end">
    <!-- Status Filter -->
    <div>
      <label for="status" class="label mb-1">Status</label>
      <select
        id="status"
        class="input"
        value={filters.status || ''}
        onchange={(e) => onchange({ status: e.currentTarget.value || undefined })}
      >
        <option value="">All Statuses</option>
        {#each ALL_STATUSES as status}
          <option value={status}>{STATUS_LABELS[status]}</option>
        {/each}
      </select>
    </div>

    <!-- Category Filter -->
    <div>
      <label for="category" class="label mb-1">Category</label>
      <select
        id="category"
        class="input"
        value={filters.companyCategory || ''}
        onchange={(e) => onchange({ companyCategory: (e.currentTarget.value as CompanyCategory) || undefined })}
      >
        <option value="">All Categories</option>
        {#each ALL_CATEGORIES as category}
          <option value={category}>{CATEGORY_LABELS[category]}</option>
        {/each}
      </select>
    </div>

    <!-- Source Filter -->
    <div>
      <label for="source" class="label mb-1">Source</label>
      <select
        id="source"
        class="input"
        value={filters.jobSource || ''}
        onchange={(e) => onchange({ jobSource: (e.currentTarget.value as JobSource) || undefined })}
      >
        <option value="">All Sources</option>
        {#each ALL_SOURCES as source}
          <option value={source}>{SOURCE_LABELS[source]}</option>
        {/each}
      </select>
    </div>

    <!-- Skills Match Filter -->
    <div>
      <label for="skills" class="label mb-1">Min Skills Match</label>
      <select
        id="skills"
        class="input"
        value={filters.skillsMatchMin || ''}
        onchange={(e) => onchange({ skillsMatchMin: e.currentTarget.value ? Number(e.currentTarget.value) : undefined })}
      >
        <option value="">Any</option>
        <option value="2">2+</option>
        <option value="3">3+</option>
        <option value="4">4+</option>
        <option value="5">5</option>
      </select>
    </div>

    <!-- Sort -->
    <div class="sm:col-span-2 lg:col-span-1">
      <label for="sort" class="label mb-1">Sort By</label>
      <div class="flex gap-2">
        <select
          id="sort"
          class="input flex-1"
          value={filters.sortBy}
          onchange={(e) => onchange({ sortBy: e.currentTarget.value as FilterState['sortBy'] })}
        >
          <option value="dateApplied">Date Applied</option>
          <option value="companyName">Company Name</option>
          <option value="updatedAt">Last Updated</option>
        </select>
        <button
          type="button"
          class="btn-secondary px-3"
          onclick={() => onchange({ sortDir: filters.sortDir === 'asc' ? 'desc' : 'asc' })}
          aria-label="Toggle sort direction"
        >
          {#if filters.sortDir === 'asc'}
            <svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 15l7-7 7 7" />
            </svg>
          {:else}
            <svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7" />
            </svg>
          {/if}
        </button>
      </div>
    </div>
  </div>

  <div class="mt-4 flex items-center justify-between">
    <div class="flex items-center gap-4">
      <label class="flex items-center gap-2 text-sm text-gray-700 dark:text-gray-300">
        <input
          type="checkbox"
          class="rounded border-gray-300 text-primary-600 focus:ring-primary-500"
          checked={filters.includeArchived}
          onchange={(e) => onchange({ includeArchived: e.currentTarget.checked })}
        />
        Include archived
      </label>
      {#if hasActiveFilters}
        <button type="button" class="text-sm text-primary-600 hover:text-primary-700" onclick={onreset}>
          Clear filters
        </button>
      {/if}
    </div>
    <span class="text-sm text-gray-500 dark:text-gray-400">
      Showing {resultCount} of {totalCount} applications
    </span>
  </div>
</div>
