// lambda-react-ui/src/components/interviews/InterviewStageList.tsx
import { useMemo, useState } from 'react';
import { Button } from '@/components/ui/Button';
import { useApplicationStore } from '@/stores/applicationStore';
import type { CreateInterviewStageInput, InterviewStage, UpdateInterviewStageInput } from '@/types/application';
import { InterviewStageForm } from './InterviewStageForm';
import { InterviewStageItem } from './InterviewStageItem';

interface InterviewStageListProps {
  appId: string;
  stages: InterviewStage[];
}

export function InterviewStageList({ appId, stages }: InterviewStageListProps) {
  const [creating, setCreating] = useState(false);
  const addStage = useApplicationStore((state) => state.addStage);
  const updateStage = useApplicationStore((state) => state.updateStage);
  const removeStage = useApplicationStore((state) => state.removeStage);
  const addDefaultStages = useApplicationStore((state) => state.addDefaultStages);

  const sortedStages = useMemo(
    () => [...stages].sort((a, b) => a.order - b.order),
    [stages]
  );
  const completedCount = sortedStages.filter((stage) => stage.isCompleted).length;
  const firstIncompleteId = sortedStages.find((stage) => !stage.isCompleted)?.id;

  const handleCreate = async (payload: CreateInterviewStageInput | UpdateInterviewStageInput) => {
    await addStage(appId, payload as CreateInterviewStageInput);
    setCreating(false);
  };

  return (
    <section data-testid="interview-stage-list" className="space-y-3">
      <div>
        <div className="flex items-center justify-between">
          <div className="text-sm font-medium text-[var(--text-primary)]">Interview Progress</div>
          <div className="text-xs text-[var(--text-secondary)]">
            {completedCount} / {sortedStages.length || 0} completed
          </div>
        </div>
        <div className="mt-1 h-2 rounded-full bg-[var(--border-subtle)]">
          <div
            className="h-2 rounded-full bg-emerald-500"
            style={{
              width:
                sortedStages.length === 0
                  ? '0%'
                  : `${Math.round((completedCount / sortedStages.length) * 100)}%`,
            }}
          />
        </div>
      </div>

      {sortedStages.length === 0 ? (
        <div className="rounded-md border border-[var(--border-subtle)] bg-[var(--bg-card)] p-3 text-sm text-[var(--text-secondary)]">
          No interview stages yet.
        </div>
      ) : null}

      {sortedStages.map((stage, index) => (
        <InterviewStageItem
          key={stage.id}
          stage={stage}
          index={index}
          isCurrent={!stage.isCompleted && stage.id === firstIncompleteId}
          onUpdate={(stageId, payload) => updateStage(appId, stageId, payload)}
          onRemove={(stageId) => removeStage(appId, stageId)}
        />
      ))}

      {creating ? (
        <InterviewStageForm
          mode="create"
          defaultOrder={sortedStages.length}
          onSave={handleCreate}
          onCancel={() => setCreating(false)}
        />
      ) : (
        <div className="flex flex-wrap gap-2">
          <Button type="button" size="sm" variant="secondary" onClick={() => setCreating(true)}>
            Add Stage
          </Button>
          {sortedStages.length === 0 ? (
            <Button type="button" size="sm" onClick={() => void addDefaultStages(appId)}>
              Add Default Stages
            </Button>
          ) : null}
        </div>
      )}
    </section>
  );
}

// svelte-ui/src/lib/components/InterviewStageList.svelte
<script lang="ts">
  import type { InterviewStage, CreateInterviewStageInput, UpdateInterviewStageInput } from '$lib/types';
  import InterviewStageItem from './InterviewStageItem.svelte';
  import InterviewStageForm from './InterviewStageForm.svelte';

  interface Props {
    stages: InterviewStage[];
    onAdd: (input: CreateInterviewStageInput) => Promise<void>;
    onUpdate: (stageId: string, input: UpdateInterviewStageInput) => Promise<void>;
    onRemove: (stageId: string) => Promise<void>;
  }

  let { stages, onAdd, onUpdate, onRemove }: Props = $props();

  let showAddForm = $state(false);
  let editingStage = $state<InterviewStage | null>(null);

  const sortedStages = $derived([...stages].sort((a, b) => a.order - b.order));
  const completedCount = $derived(stages.filter((s) => s.isCompleted).length);

  async function handleToggleComplete(stage: InterviewStage) {
    await onUpdate(stage.id, {
      isCompleted: !stage.isCompleted,
      completedDate: !stage.isCompleted ? new Date().toISOString().split('T')[0] : null,
    });
  }

  async function handleAddStage(input: CreateInterviewStageInput) {
    await onAdd(input);
    showAddForm = false;
  }

  async function handleUpdateStage(input: UpdateInterviewStageInput) {
    if (editingStage) {
      await onUpdate(editingStage.id, input);
      editingStage = null;
    }
  }

  async function handleDeleteStage(stageId: string) {
    if (confirm('Are you sure you want to delete this interview stage?')) {
      await onRemove(stageId);
    }
  }
</script>

<div class="space-y-2">
  <div class="flex items-center justify-between mb-4">
    <h3 class="text-lg font-semibold text-gray-900 dark:text-gray-100">
      Interview Stages
      {#if stages.length > 0}
        <span class="text-sm font-normal text-gray-500 dark:text-gray-400">
          ({completedCount}/{stages.length} completed)
        </span>
      {/if}
    </h3>
  </div>

  {#if sortedStages.length > 0}
    <div class="divide-y divide-gray-200 dark:divide-gray-700">
      {#each sortedStages as stage (stage.id)}
        <InterviewStageItem
          {stage}
          onToggleComplete={() => handleToggleComplete(stage)}
          onEdit={() => (editingStage = stage)}
          onDelete={() => handleDeleteStage(stage.id)}
        />
      {/each}
    </div>
  {:else}
    <p class="text-gray-500 dark:text-gray-400 text-sm py-4">No interview stages yet.</p>
  {/if}

  {#if showAddForm}
    <InterviewStageForm
      nextOrder={stages.length}
      onsubmit={(input) => handleAddStage(input as CreateInterviewStageInput)}
      oncancel={() => (showAddForm = false)}
    />
  {:else}
    <button type="button" class="btn-secondary mt-4" onclick={() => (showAddForm = true)}>
      <svg class="h-4 w-4 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4" />
      </svg>
      Add Stage
    </button>
  {/if}

  {#if editingStage}
    <InterviewStageForm
      stage={editingStage}
      nextOrder={editingStage.order}
      onsubmit={(input) => handleUpdateStage(input as UpdateInterviewStageInput)}
      oncancel={() => (editingStage = null)}
    />
  {/if}
</div>
