// lambda-react-ui/src/components/interviews/InterviewStageForm.tsx
import { useState } from 'react';
import { Button } from '@/components/ui/Button';
import { Input } from '@/components/ui/Input';
import { TextArea } from '@/components/ui/TextArea';
import { RatingInput } from '@/components/ui/Rating';
import { getTodayDate } from '@/lib/utils';
import type { CreateInterviewStageInput, InterviewStage, UpdateInterviewStageInput } from '@/types/application';

interface InterviewStageFormProps {
  mode: 'create' | 'edit';
  defaultOrder: number;
  initialValues?: InterviewStage;
  saving?: boolean;
  onSave: (payload: CreateInterviewStageInput | UpdateInterviewStageInput) => Promise<void>;
  onDelete?: () => Promise<void>;
  onCancel: () => void;
}

export function InterviewStageForm({
  mode,
  defaultOrder,
  initialValues,
  saving = false,
  onSave,
  onDelete,
  onCancel,
}: InterviewStageFormProps) {
  const [name, setName] = useState(initialValues?.name ?? '');
  const [isCompleted, setIsCompleted] = useState(initialValues?.isCompleted ?? false);
  const [completedDate, setCompletedDate] = useState(initialValues?.completedDate ?? '');
  const [notes, setNotes] = useState(initialValues?.notes ?? '');
  const [performanceRating, setPerformanceRating] = useState<number | null>(initialValues?.performanceRating ?? null);
  const [error, setError] = useState<string | null>(null);

  const handleCompletedToggle = (checked: boolean) => {
    setIsCompleted(checked);
    if (checked && !completedDate) {
      setCompletedDate(getTodayDate());
    }
    if (!checked) {
      setCompletedDate('');
    }
  };

  const handleSave = async () => {
    if (!name.trim()) {
      setError('Stage name is required.');
      return;
    }

    setError(null);

    try {
      if (mode === 'create') {
        await onSave({
          name: name.trim(),
          order: defaultOrder,
          isCompleted,
          completedDate: isCompleted && completedDate ? completedDate : undefined,
          notes: notes.trim() || undefined,
          performanceRating,
        });
        return;
      }

      await onSave({
        name: name.trim(),
        isCompleted,
        completedDate: isCompleted ? completedDate || null : null,
        notes: notes.trim() || null,
        performanceRating,
      });
    } catch (caught) {
      setError(caught instanceof Error ? caught.message : 'Failed to save stage.');
    }
  };

  return (
    <form
      data-testid="stage-form"
      className="mt-2 rounded-md border border-[var(--border-subtle)] p-3"
      onSubmit={(event) => event.preventDefault()}
    >
      <div className="grid gap-2">
        <Input
          label="Stage Name"
          placeholder={mode === 'create' ? 'Phone Screen, Technical Interview...' : 'e.g., Technical Interview'}
          value={name}
          onChange={(event) => setName(event.target.value)}
          required
        />

        <label className="inline-flex items-center gap-2 text-sm text-[var(--text-primary)]">
          <input
            type="checkbox"
            checked={isCompleted}
            onChange={(event) => handleCompletedToggle(event.target.checked)}
          />
          Completed
        </label>

        {isCompleted ? (
          <Input
            label="Completed Date"
            type="date"
            value={completedDate}
            onChange={(event) => setCompletedDate(event.target.value)}
          />
        ) : null}

        <div>
          <div className="mb-1 text-sm font-medium text-[var(--text-primary)]">Performance Rating</div>
          <RatingInput value={performanceRating} onChange={setPerformanceRating} />
        </div>

        <TextArea label="Notes" value={notes} onChange={(event) => setNotes(event.target.value)} />
      </div>

      {error ? <div className="mt-2 text-xs text-[var(--status-rejected)]">{error}</div> : null}

      <div className="mt-3 flex justify-end gap-2">
        <Button type="button" variant="secondary" onClick={onCancel}>
          Cancel
        </Button>
        {mode === 'edit' ? (
          <Button
            type="button"
            variant="danger"
            onClick={() => {
              if (onDelete) {
                onDelete().catch((caught: unknown) => {
                  setError(caught instanceof Error ? caught.message : 'Failed to delete stage.');
                });
              }
            }}
          >
            Delete Stage
          </Button>
        ) : null}
        <Button type="button" onClick={() => void handleSave()} loading={saving}>
          <span data-testid="stage-form-save">{mode === 'create' ? 'Add Stage' : 'Save Stage'}</span>
        </Button>
      </div>
    </form>
  );
}

// svelte-ui/src/lib/components/InterviewStageForm.svelte
<script lang="ts">
  import type { InterviewStage, CreateInterviewStageInput, UpdateInterviewStageInput } from '$lib/types';
  import RatingInput from './RatingInput.svelte';

  interface Props {
    stage?: InterviewStage;
    nextOrder: number;
    onsubmit: (input: CreateInterviewStageInput | UpdateInterviewStageInput) => Promise<void>;
    oncancel: () => void;
  }

  let { stage, nextOrder, onsubmit, oncancel }: Props = $props();

  let name = $state(stage?.name || '');
  let order = $state(stage?.order ?? nextOrder);
  let isCompleted = $state(stage?.isCompleted || false);
  let completedDate = $state(stage?.completedDate || '');
  let notes = $state(stage?.notes || '');
  let performanceRating = $state<number | null>(stage?.performanceRating ?? null);
  let submitting = $state(false);
  let error = $state<string | null>(null);

  const isEditing = $derived(!!stage);

  async function handleSubmit(e: Event) {
    e.preventDefault();
    error = null;
    submitting = true;

    try {
      if (isEditing) {
        const input: UpdateInterviewStageInput = {
          name,
          order,
          isCompleted,
          completedDate: completedDate || null,
          notes: notes || null,
          performanceRating,
        };
        await onsubmit(input);
      } else {
        const input: CreateInterviewStageInput = {
          name,
          order,
          isCompleted,
          completedDate: completedDate || undefined,
          notes: notes || undefined,
          performanceRating: performanceRating ?? undefined,
        };
        await onsubmit(input);
      }
    } catch (err) {
      error = err instanceof Error ? err.message : 'Failed to save stage';
    } finally {
      submitting = false;
    }
  }
</script>

<div class="card p-4 mt-4">
  <form onsubmit={handleSubmit} class="space-y-4">
    <h4 class="font-medium text-gray-900 dark:text-gray-100">
      {isEditing ? 'Edit Interview Stage' : 'Add Interview Stage'}
    </h4>

    {#if error}
      <div class="text-red-600 dark:text-red-400 text-sm">{error}</div>
    {/if}

    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
      <div>
        <label for="stage-name" class="label mb-1">Stage Name *</label>
        <input
          id="stage-name"
          type="text"
          class="input"
          bind:value={name}
          placeholder="Phone Screen, Technical Interview..."
          required
        />
      </div>

      <div>
        <label for="stage-order" class="label mb-1">Order</label>
        <input id="stage-order" type="number" class="input" bind:value={order} min="0" />
      </div>
    </div>

    <div class="flex items-center gap-4">
      <label class="flex items-center gap-2">
        <input
          type="checkbox"
          class="rounded border-gray-300 text-primary-600 focus:ring-primary-500"
          bind:checked={isCompleted}
        />
        <span class="text-sm text-gray-700 dark:text-gray-300">Completed</span>
      </label>

      {#if isCompleted}
        <div class="flex-1 max-w-[200px]">
          <input type="date" class="input" bind:value={completedDate} />
        </div>
      {/if}
    </div>

    <div>
      <label class="label mb-1">Performance Rating</label>
      <RatingInput value={performanceRating} onchange={(v) => (performanceRating = v)} />
    </div>

    <div>
      <label for="stage-notes" class="label mb-1">Notes</label>
      <textarea
        id="stage-notes"
        class="input min-h-[80px]"
        bind:value={notes}
        placeholder="Notes about this interview stage..."
      ></textarea>
    </div>

    <div class="flex justify-end gap-2">
      <button type="button" class="btn-secondary" onclick={oncancel} disabled={submitting}>
        Cancel
      </button>
      <button type="submit" class="btn-primary" disabled={submitting || !name.trim()}>
        {submitting ? 'Saving...' : isEditing ? 'Save Changes' : 'Add Stage'}
      </button>
    </div>
  </form>
</div>
