// src/components/common/Header.tsx
import type { ReactNode } from 'react';
import { cn } from '@/lib/utils';

export interface HeaderProps {
  title?: string;
  children?: ReactNode;
  className?: string;
}

export function Header({
  title = 'Job Application Tracker',
  children,
  className,
}: HeaderProps): ReactNode {
  return (
    <header
      className={cn(
        'bg-white border-b border-gray-200 sticky top-0 z-40',
        className
      )}
    >
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex items-center justify-between h-16">
          <div className="flex items-center">
            <h1 className="text-xl font-bold text-gray-900">{title}</h1>
          </div>
          {children && (
            <div className="flex items-center gap-4">
              {children}
            </div>
          )}
        </div>
      </div>
    </header>
  );
}

// angular-ui/src/app/shared/components/header/header.component.ts
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [RouterLink],
  template: `
    <header class="bg-white border-b border-gray-200 shadow-sm">
      <div class="container mx-auto px-4 py-4 max-w-7xl flex items-center justify-between">
        <div>
          <a routerLink="/" class="text-xl font-bold text-gray-900 hover:text-blue-600">
            Application Tracker
          </a>
          <p class="text-xs text-gray-500 mt-0.5">Angular &bull; Go Gin &bull; pgx/sqlc</p>
        </div>
        <nav>
          <a routerLink="/" class="text-sm text-gray-600 hover:text-gray-900">
            Applications
          </a>
        </nav>
      </div>
    </header>
  `,
})
export class HeaderComponent {}
