// tanstack-ui/src/components/common/Header.tsx
import { useState, useEffect } from "react";
import { Link, useNavigate } from "@tanstack/react-router";
import { Button } from "../ui";

export function Header() {
  const navigate = useNavigate();
  const [isDark, setIsDark] = useState(() => {
    if (typeof window !== "undefined") {
      return (
        localStorage.getItem("app-theme") === "dark" ||
        (!localStorage.getItem("app-theme") &&
          window.matchMedia("(prefers-color-scheme: dark)").matches)
      );
    }
    return false;
  });

  useEffect(() => {
    if (isDark) {
      document.documentElement.classList.add("dark");
      localStorage.setItem("app-theme", "dark");
    } else {
      document.documentElement.classList.remove("dark");
      localStorage.setItem("app-theme", "light");
    }
  }, [isDark]);

  return (
    <header className="bg-white dark:bg-gray-800 border-b border-gray-200 dark:border-gray-700">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex items-center justify-between h-16">
          {/* Logo / Title */}
          <Link to="/" className="flex items-center gap-3">
            <svg
              className="w-8 h-8 text-primary-600"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M21 13.255A23.931 23.931 0 0112 15c-3.183 0-6.22-.62-9-1.745M16 6V4a2 2 0 00-2-2h-4a2 2 0 00-2 2v2m4 6h.01M5 20h14a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"
              />
            </svg>
            <h1 className="text-xl font-bold text-gray-900 dark:text-white">
              Job Application Tracker (React - NestJS - Drizzle)
            </h1>
          </Link>

          {/* Actions */}
          <div className="flex items-center gap-3">
            {/* Theme Toggle */}
            <button
              onClick={() => setIsDark(!isDark)}
              className="p-2 text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-200 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-700"
              aria-label={isDark ? "Switch to light mode" : "Switch to dark mode"}
            >
              {isDark ? (
                <svg
                  className="w-5 h-5"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M12 3v1m0 16v1m9-9h-1M4 12H3m15.364 6.364l-.707-.707M6.343 6.343l-.707-.707m12.728 0l-.707.707M6.343 17.657l-.707.707M16 12a4 4 0 11-8 0 4 4 0 018 0z"
                  />
                </svg>
              ) : (
                <svg
                  className="w-5 h-5"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M20.354 15.354A9 9 0 018.646 3.646 9.003 9.003 0 0012 21a9.003 9.003 0 008.354-5.646z"
                  />
                </svg>
              )}
            </button>

            {/* Add Application Button */}
            <Button onClick={() => navigate({ to: "/applications/new" })}>
              <svg
                className="w-4 h-4 mr-2"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M12 4v16m8-8H4"
                />
              </svg>
              Add Application
            </Button>
          </div>
        </div>
      </div>
    </header>
  );
}

// angular-ui/src/app/shared/components/header/header.component.ts
import { ChangeDetectorRef, Component, OnInit, inject } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [RouterLink],
  template: `
    <header class="bg-white border-b border-gray-200 shadow-sm dark:bg-gray-900 dark:border-gray-700">
      <div class="container mx-auto px-4 py-4 max-w-7xl flex items-center justify-between">
        <div>
          <a routerLink="/" class="text-xl font-bold text-gray-900 hover:text-blue-600 dark:text-white">
            Application Tracker
          </a>
          <p class="text-xs text-gray-500 mt-0.5 dark:text-gray-400">Angular &bull; Go Gin &bull; pgx/sqlc</p>
        </div>
        <div class="flex items-center gap-3">
          <nav>
            <a routerLink="/" class="text-sm text-gray-600 hover:text-gray-900 dark:text-gray-300">
              Applications
            </a>
          </nav>
          @if (isDark) {
            <button
              type="button"
              aria-label="switch to light mode"
              (click)="toggleDarkMode()"
              class="p-2 rounded hover:bg-gray-100 text-gray-600 dark:hover:bg-gray-700 dark:text-gray-300"
            >
              &#9728;
            </button>
          } @else {
            <button
              type="button"
              aria-label="switch to dark mode"
              (click)="toggleDarkMode()"
              class="p-2 rounded hover:bg-gray-100 text-gray-600 dark:hover:bg-gray-700 dark:text-gray-300"
            >
              &#9790;
            </button>
          }
        </div>
      </div>
    </header>
  `,
})
export class HeaderComponent implements OnInit {
  isDark = false;
  private cdr = inject(ChangeDetectorRef);

  ngOnInit() {
    const stored = localStorage.getItem('app-theme');
    if (stored === 'dark') {
      this.isDark = true;
      document.documentElement.classList.add('dark');
    } else {
      document.documentElement.classList.remove('dark');
    }
  }

  toggleDarkMode() {
    this.isDark = !this.isDark;
    if (this.isDark) {
      document.documentElement.classList.add('dark');
      localStorage.setItem('app-theme', 'dark');
    } else {
      document.documentElement.classList.remove('dark');
      localStorage.setItem('app-theme', 'light');
    }
    this.cdr.detectChanges();
  }
}
