// svelte-ui/src/lib/components/InterviewStageList.svelte
<script lang="ts">
  import type { InterviewStage, CreateInterviewStageInput, UpdateInterviewStageInput } from '$lib/types';
  import InterviewStageItem from './InterviewStageItem.svelte';
  import InterviewStageForm from './InterviewStageForm.svelte';

  interface Props {
    stages: InterviewStage[];
    onAdd: (input: CreateInterviewStageInput) => Promise<void>;
    onUpdate: (stageId: string, input: UpdateInterviewStageInput) => Promise<void>;
    onRemove: (stageId: string) => Promise<void>;
  }

  let { stages, onAdd, onUpdate, onRemove }: Props = $props();

  let showAddForm = $state(false);
  let editingStage = $state<InterviewStage | null>(null);

  const sortedStages = $derived([...stages].sort((a, b) => a.order - b.order));
  const completedCount = $derived(stages.filter((s) => s.isCompleted).length);

  async function handleToggleComplete(stage: InterviewStage) {
    await onUpdate(stage.id, {
      isCompleted: !stage.isCompleted,
      completedDate: !stage.isCompleted ? new Date().toISOString().split('T')[0] : null,
    });
  }

  async function handleAddStage(input: CreateInterviewStageInput) {
    await onAdd(input);
    showAddForm = false;
  }

  async function handleUpdateStage(input: UpdateInterviewStageInput) {
    if (editingStage) {
      await onUpdate(editingStage.id, input);
      editingStage = null;
    }
  }

  async function handleDeleteStage(stageId: string) {
    if (confirm('Are you sure you want to delete this interview stage?')) {
      await onRemove(stageId);
    }
  }
</script>

<div class="space-y-2">
  <div class="flex items-center justify-between mb-4">
    <h3 class="text-lg font-semibold text-gray-900 dark:text-gray-100">
      Interview Stages
      {#if stages.length > 0}
        <span class="text-sm font-normal text-gray-500 dark:text-gray-400">
          ({completedCount}/{stages.length} completed)
        </span>
      {/if}
    </h3>
  </div>

  {#if sortedStages.length > 0}
    <div class="divide-y divide-gray-200 dark:divide-gray-700">
      {#each sortedStages as stage (stage.id)}
        <InterviewStageItem
          {stage}
          onToggleComplete={() => handleToggleComplete(stage)}
          onEdit={() => (editingStage = stage)}
          onDelete={() => handleDeleteStage(stage.id)}
        />
      {/each}
    </div>
  {:else}
    <p class="text-gray-500 dark:text-gray-400 text-sm py-4">No interview stages yet.</p>
  {/if}

  {#if showAddForm}
    <InterviewStageForm
      nextOrder={stages.length}
      onsubmit={(input) => handleAddStage(input as CreateInterviewStageInput)}
      oncancel={() => (showAddForm = false)}
    />
  {:else}
    <button type="button" class="btn-secondary mt-4" onclick={() => (showAddForm = true)}>
      <svg class="h-4 w-4 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4" />
      </svg>
      Add Stage
    </button>
  {/if}

  {#if editingStage}
    <InterviewStageForm
      stage={editingStage}
      nextOrder={editingStage.order}
      onsubmit={(input) => handleUpdateStage(input as UpdateInterviewStageInput)}
      oncancel={() => (editingStage = null)}
    />
  {/if}
</div>

// react-ui/src/components/interviews/InterviewStageList.tsx
import { useState } from "react";
import type {
  InterviewStage,
  CreateInterviewStageInput,
  UpdateInterviewStageInput,
} from "../../types/application";
import { Button } from "../ui";
import { InterviewStageItem } from "./InterviewStageItem";
import { InterviewStageForm } from "./InterviewStageForm";
import { DEFAULT_INTERVIEW_STAGES } from "../../lib/constants";

interface InterviewStageListProps {
  stages: InterviewStage[];
  onAdd: (input: CreateInterviewStageInput) => Promise<void>;
  onUpdate: (stageId: string, input: UpdateInterviewStageInput) => Promise<void>;
  onRemove: (stageId: string) => Promise<void>;
}

export function InterviewStageList({
  stages,
  onAdd,
  onUpdate,
  onRemove,
}: InterviewStageListProps) {
  const [showForm, setShowForm] = useState(false);
  const [editingStage, setEditingStage] = useState<InterviewStage | null>(null);
  const [isLoading, setIsLoading] = useState(false);

  const sortedStages = [...stages].sort((a, b) => a.order - b.order);
  const completedCount = stages.filter((s) => s.isCompleted).length;
  const nextOrder = stages.length > 0 ? Math.max(...stages.map((s) => s.order)) + 1 : 0;

  const handleAddStage = async (
    data: CreateInterviewStageInput | UpdateInterviewStageInput
  ) => {
    setIsLoading(true);
    try {
      await onAdd(data as CreateInterviewStageInput);
    } finally {
      setIsLoading(false);
    }
  };

  const handleUpdateStage = async (data: UpdateInterviewStageInput) => {
    if (!editingStage) return;
    setIsLoading(true);
    try {
      await onUpdate(editingStage.id, data);
      setEditingStage(null);
    } finally {
      setIsLoading(false);
    }
  };

  const handleToggleComplete = async (
    stage: InterviewStage,
    isCompleted: boolean,
    completedDate?: string | null
  ) => {
    await onUpdate(stage.id, { isCompleted, completedDate });
  };

  const handleAddDefaults = async () => {
    setIsLoading(true);
    try {
      for (let i = 0; i < DEFAULT_INTERVIEW_STAGES.length; i++) {
        await onAdd({
          name: DEFAULT_INTERVIEW_STAGES[i],
          order: nextOrder + i,
          isCompleted: false,
        });
      }
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="space-y-3">
      {/* Progress Summary */}
      {stages.length > 0 && (
        <div className="flex items-center justify-between text-sm">
          <span className="text-gray-500 dark:text-gray-400">
            {completedCount} of {stages.length} completed
          </span>
          <div className="flex-1 mx-4 h-2 bg-gray-200 dark:bg-gray-700 rounded-full overflow-hidden">
            <div
              className="h-full bg-primary-500 transition-all"
              style={{
                width: `${stages.length > 0 ? (completedCount / stages.length) * 100 : 0}%`,
              }}
            />
          </div>
        </div>
      )}

      {/* Stage List */}
      {sortedStages.length > 0 ? (
        <div className="space-y-2">
          {sortedStages.map((stage) => (
            <InterviewStageItem
              key={stage.id}
              stage={stage}
              onToggleComplete={(isCompleted, completedDate) =>
                handleToggleComplete(stage, isCompleted, completedDate)
              }
              onEdit={() => setEditingStage(stage)}
              onDelete={() => onRemove(stage.id)}
            />
          ))}
        </div>
      ) : (
        <div className="text-center py-6 text-gray-500 dark:text-gray-400">
          <p className="mb-3">No interview stages yet</p>
          <Button
            variant="secondary"
            size="sm"
            onClick={handleAddDefaults}
            disabled={isLoading}
          >
            {isLoading ? "Adding..." : "Add Default Stages"}
          </Button>
        </div>
      )}

      {/* Add Button */}
      <Button
        variant="ghost"
        size="sm"
        onClick={() => setShowForm(true)}
        className="w-full justify-center"
      >
        <svg
          className="w-4 h-4 mr-2"
          fill="none"
          viewBox="0 0 24 24"
          stroke="currentColor"
        >
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth={2}
            d="M12 4v16m8-8H4"
          />
        </svg>
        Add Stage
      </Button>

      {/* Add/Edit Form Modal */}
      <InterviewStageForm
        isOpen={showForm || !!editingStage}
        onClose={() => {
          setShowForm(false);
          setEditingStage(null);
        }}
        onSubmit={editingStage ? handleUpdateStage : handleAddStage}
        stage={editingStage}
        nextOrder={nextOrder}
        isLoading={isLoading}
      />
    </div>
  );
}
