// svelte-ui/src/lib/components/FilterBar.svelte
<script lang="ts">
  import type { FilterState, CompanyCategory, JobSource } from '$lib/types';
  import { ALL_STATUSES, ALL_CATEGORIES, ALL_SOURCES, STATUS_LABELS, CATEGORY_LABELS, SOURCE_LABELS } from '$lib/types';

  interface Props {
    filters: FilterState;
    resultCount: number;
    totalCount: number;
    onchange: (filters: Partial<FilterState>) => void;
    onreset: () => void;
  }

  let { filters, resultCount, totalCount, onchange, onreset }: Props = $props();

  const hasActiveFilters = $derived(
    filters.status || filters.companyCategory || filters.jobSource || filters.skillsMatchMin || filters.includeArchived
  );
</script>

<div class="bg-white dark:bg-gray-800 p-4 rounded-lg shadow-sm border border-gray-200 dark:border-gray-700">
  <div class="flex flex-wrap gap-4 items-end">
    <!-- Status Filter -->
    <div class="flex-1 min-w-[150px]">
      <label for="status" class="label mb-1">Status</label>
      <select
        id="status"
        class="input"
        value={filters.status || ''}
        onchange={(e) => onchange({ status: e.currentTarget.value || undefined })}
      >
        <option value="">All Statuses</option>
        {#each ALL_STATUSES as status}
          <option value={status}>{STATUS_LABELS[status]}</option>
        {/each}
      </select>
    </div>

    <!-- Category Filter -->
    <div class="flex-1 min-w-[150px]">
      <label for="category" class="label mb-1">Category</label>
      <select
        id="category"
        class="input"
        value={filters.companyCategory || ''}
        onchange={(e) => onchange({ companyCategory: (e.currentTarget.value as CompanyCategory) || undefined })}
      >
        <option value="">All Categories</option>
        {#each ALL_CATEGORIES as category}
          <option value={category}>{CATEGORY_LABELS[category]}</option>
        {/each}
      </select>
    </div>

    <!-- Source Filter -->
    <div class="flex-1 min-w-[150px]">
      <label for="source" class="label mb-1">Source</label>
      <select
        id="source"
        class="input"
        value={filters.jobSource || ''}
        onchange={(e) => onchange({ jobSource: (e.currentTarget.value as JobSource) || undefined })}
      >
        <option value="">All Sources</option>
        {#each ALL_SOURCES as source}
          <option value={source}>{SOURCE_LABELS[source]}</option>
        {/each}
      </select>
    </div>

    <!-- Skills Match Filter -->
    <div class="flex-1 min-w-[150px]">
      <label for="skills" class="label mb-1">Min Skills Match</label>
      <select
        id="skills"
        class="input"
        value={filters.skillsMatchMin || ''}
        onchange={(e) => onchange({ skillsMatchMin: e.currentTarget.value ? Number(e.currentTarget.value) : undefined })}
      >
        <option value="">Any</option>
        <option value="2">2+</option>
        <option value="3">3+</option>
        <option value="4">4+</option>
        <option value="5">5</option>
      </select>
    </div>

    <!-- Sort -->
    <div class="flex-1 min-w-[200px]">
      <label for="sort" class="label mb-1">Sort By</label>
      <div class="flex gap-2">
        <select
          id="sort"
          class="input flex-1"
          value={filters.sortBy}
          onchange={(e) => onchange({ sortBy: e.currentTarget.value as FilterState['sortBy'] })}
        >
          <option value="dateApplied">Date Applied</option>
          <option value="companyName">Company Name</option>
          <option value="updatedAt">Last Updated</option>
        </select>
        <button
          type="button"
          class="btn-secondary px-3"
          onclick={() => onchange({ sortDir: filters.sortDir === 'asc' ? 'desc' : 'asc' })}
          aria-label="Toggle sort direction"
        >
          {#if filters.sortDir === 'asc'}
            <svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 15l7-7 7 7" />
            </svg>
          {:else}
            <svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7" />
            </svg>
          {/if}
        </button>
      </div>
    </div>
  </div>

  <div class="mt-4 flex items-center justify-between">
    <div class="flex items-center gap-4">
      <label class="flex items-center gap-2 text-sm text-gray-700 dark:text-gray-300">
        <input
          type="checkbox"
          class="rounded border-gray-300 text-primary-600 focus:ring-primary-500"
          checked={filters.includeArchived}
          onchange={(e) => onchange({ includeArchived: e.currentTarget.checked })}
        />
        Include archived
      </label>
      {#if hasActiveFilters}
        <button type="button" class="text-sm text-primary-600 hover:text-primary-700" onclick={onreset}>
          Clear filters
        </button>
      {/if}
    </div>
    <span class="text-sm text-gray-500 dark:text-gray-400">
      Showing {resultCount} of {totalCount} applications
    </span>
  </div>
</div>

// tanstack-ui/src/components/applications/FilterBar.tsx
import type {
  FilterState,
  ApplicationStatus,
  CompanyCategory,
  JobSource,
  SortState,
} from "../../types/application";
import { Button, Select, Checkbox } from "../ui";
import {
  APPLICATION_STATUSES,
  COMPANY_CATEGORIES,
  JOB_SOURCES,
} from "../../lib/constants";

interface FilterBarProps {
  filters: FilterState;
  sorting: SortState;
  resultCount: number;
  totalCount: number;
  onStatusChange: (statuses: ApplicationStatus[]) => void;
  onCategoryChange: (category: CompanyCategory | null) => void;
  onSourceChange: (source: JobSource | null) => void;
  onSkillsMatchChange: (min: number | null) => void;
  onIncludeArchivedChange: (include: boolean) => void;
  onSortByChange: (sortBy: SortState["sortBy"]) => void;
  onSortDirToggle: () => void;
  onClearFilters: () => void;
  hasActiveFilters: boolean;
  activeFilterCount: number;
}

const SORT_OPTIONS = [
  { value: "dateApplied", label: "Date Applied" },
  { value: "companyName", label: "Company Name" },
  { value: "updatedAt", label: "Last Updated" },
];

const SKILLS_MATCH_OPTIONS = [
  { value: "", label: "Any" },
  { value: "2", label: "2+ stars" },
  { value: "3", label: "3+ stars" },
  { value: "4", label: "4+ stars" },
  { value: "5", label: "5 stars" },
];

export function FilterBar({
  filters,
  sorting,
  resultCount,
  totalCount,
  onStatusChange,
  onCategoryChange,
  onSourceChange,
  onSkillsMatchChange,
  onIncludeArchivedChange,
  onSortByChange,
  onSortDirToggle,
  onClearFilters,
  hasActiveFilters,
  activeFilterCount,
}: FilterBarProps) {
  return (
    <div className="space-y-4">
      {/* Filter Controls */}
      <div className="flex flex-wrap items-end gap-4">
        {/* Status Filter */}
        <div className="w-40">
          <Select
            label="Status"
            value={filters.status[0] || ""}
            onChange={(e) => {
              const value = e.target.value as ApplicationStatus;
              onStatusChange(value ? [value] : []);
            }}
            options={APPLICATION_STATUSES}
            placeholder="All statuses"
          />
        </div>

        {/* Category Filter */}
        <div className="w-44">
          <Select
            label="Category"
            value={filters.companyCategory || ""}
            onChange={(e) =>
              onCategoryChange(
                (e.target.value as CompanyCategory) || null
              )
            }
            options={COMPANY_CATEGORIES}
            placeholder="All categories"
          />
        </div>

        {/* Source Filter */}
        <div className="w-40">
          <Select
            label="Source"
            value={filters.jobSource || ""}
            onChange={(e) =>
              onSourceChange((e.target.value as JobSource) || null)
            }
            options={JOB_SOURCES}
            placeholder="All sources"
          />
        </div>

        {/* Skills Match Filter */}
        <div className="w-32">
          <Select
            label="Skills"
            value={filters.skillsMatchMin?.toString() || ""}
            onChange={(e) =>
              onSkillsMatchChange(
                e.target.value ? parseInt(e.target.value) : null
              )
            }
            options={SKILLS_MATCH_OPTIONS}
          />
        </div>

        {/* Include Archived */}
        <div className="pb-2">
          <Checkbox
            label="Show archived"
            checked={filters.includeArchived}
            onChange={(e) => onIncludeArchivedChange(e.target.checked)}
          />
        </div>

        {/* Clear Filters */}
        {hasActiveFilters && (
          <div className="pb-2">
            <Button variant="ghost" size="sm" onClick={onClearFilters}>
              Clear ({activeFilterCount})
            </Button>
          </div>
        )}
      </div>

      {/* Sort Controls and Results Count */}
      <div className="flex items-center justify-between">
        <div className="text-sm text-gray-500 dark:text-gray-400">
          {resultCount === totalCount
            ? `${totalCount} application${totalCount !== 1 ? "s" : ""}`
            : `${resultCount} of ${totalCount} applications`}
        </div>

        <div className="flex items-center gap-2">
          <Select
            value={sorting.sortBy}
            onChange={(e) =>
              onSortByChange(e.target.value as SortState["sortBy"])
            }
            options={SORT_OPTIONS}
            className="w-36"
          />
          <Button
            variant="ghost"
            size="sm"
            onClick={onSortDirToggle}
            aria-label={
              sorting.sortDir === "asc"
                ? "Sort ascending"
                : "Sort descending"
            }
          >
            {sorting.sortDir === "asc" ? (
              <svg
                className="w-5 h-5"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M3 4h13M3 8h9m-9 4h6m4 0l4-4m0 0l4 4m-4-4v12"
                />
              </svg>
            ) : (
              <svg
                className="w-5 h-5"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M3 4h13M3 8h9m-9 4h9m5-4v12m0 0l-4-4m4 4l4-4"
                />
              </svg>
            )}
          </Button>
        </div>
      </div>
    </div>
  );
}
