// svelte-ui/src/lib/components/FilterBar.svelte
<script lang="ts">
  import type { FilterState, CompanyCategory, JobSource } from '$lib/types';
  import { ALL_STATUSES, ALL_CATEGORIES, ALL_SOURCES, STATUS_LABELS, CATEGORY_LABELS, SOURCE_LABELS } from '$lib/types';

  interface Props {
    filters: FilterState;
    resultCount: number;
    totalCount: number;
    onchange: (filters: Partial<FilterState>) => void;
    onreset: () => void;
  }

  let { filters, resultCount, totalCount, onchange, onreset }: Props = $props();

  const hasActiveFilters = $derived(
    filters.status || filters.companyCategory || filters.jobSource || filters.skillsMatchMin || filters.includeArchived
  );
</script>

<div class="bg-white dark:bg-gray-800 p-4 rounded-lg shadow-sm border border-gray-200 dark:border-gray-700">
  <div class="flex flex-wrap gap-4 items-end">
    <!-- Status Filter -->
    <div class="flex-1 min-w-[150px]">
      <label for="status" class="label mb-1">Status</label>
      <select
        id="status"
        class="input"
        value={filters.status || ''}
        onchange={(e) => onchange({ status: e.currentTarget.value || undefined })}
      >
        <option value="">All Statuses</option>
        {#each ALL_STATUSES as status}
          <option value={status}>{STATUS_LABELS[status]}</option>
        {/each}
      </select>
    </div>

    <!-- Category Filter -->
    <div class="flex-1 min-w-[150px]">
      <label for="category" class="label mb-1">Category</label>
      <select
        id="category"
        class="input"
        value={filters.companyCategory || ''}
        onchange={(e) => onchange({ companyCategory: (e.currentTarget.value as CompanyCategory) || undefined })}
      >
        <option value="">All Categories</option>
        {#each ALL_CATEGORIES as category}
          <option value={category}>{CATEGORY_LABELS[category]}</option>
        {/each}
      </select>
    </div>

    <!-- Source Filter -->
    <div class="flex-1 min-w-[150px]">
      <label for="source" class="label mb-1">Source</label>
      <select
        id="source"
        class="input"
        value={filters.jobSource || ''}
        onchange={(e) => onchange({ jobSource: (e.currentTarget.value as JobSource) || undefined })}
      >
        <option value="">All Sources</option>
        {#each ALL_SOURCES as source}
          <option value={source}>{SOURCE_LABELS[source]}</option>
        {/each}
      </select>
    </div>

    <!-- Skills Match Filter -->
    <div class="flex-1 min-w-[150px]">
      <label for="skills" class="label mb-1">Min Skills Match</label>
      <select
        id="skills"
        class="input"
        value={filters.skillsMatchMin || ''}
        onchange={(e) => onchange({ skillsMatchMin: e.currentTarget.value ? Number(e.currentTarget.value) : undefined })}
      >
        <option value="">Any</option>
        <option value="2">2+</option>
        <option value="3">3+</option>
        <option value="4">4+</option>
        <option value="5">5</option>
      </select>
    </div>

    <!-- Sort -->
    <div class="flex-1 min-w-[200px]">
      <label for="sort" class="label mb-1">Sort By</label>
      <div class="flex gap-2">
        <select
          id="sort"
          class="input flex-1"
          value={filters.sortBy}
          onchange={(e) => onchange({ sortBy: e.currentTarget.value as FilterState['sortBy'] })}
        >
          <option value="dateApplied">Date Applied</option>
          <option value="companyName">Company Name</option>
          <option value="updatedAt">Last Updated</option>
        </select>
        <button
          type="button"
          class="btn-secondary px-3"
          onclick={() => onchange({ sortDir: filters.sortDir === 'asc' ? 'desc' : 'asc' })}
          aria-label="Toggle sort direction"
        >
          {#if filters.sortDir === 'asc'}
            <svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 15l7-7 7 7" />
            </svg>
          {:else}
            <svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7" />
            </svg>
          {/if}
        </button>
      </div>
    </div>
  </div>

  <div class="mt-4 flex items-center justify-between">
    <div class="flex items-center gap-4">
      <label class="flex items-center gap-2 text-sm text-gray-700 dark:text-gray-300">
        <input
          type="checkbox"
          class="rounded border-gray-300 text-primary-600 focus:ring-primary-500"
          checked={filters.includeArchived}
          onchange={(e) => onchange({ includeArchived: e.currentTarget.checked })}
        />
        Include archived
      </label>
      {#if hasActiveFilters}
        <button type="button" class="text-sm text-primary-600 hover:text-primary-700" onclick={onreset}>
          Clear filters
        </button>
      {/if}
    </div>
    <span class="text-sm text-gray-500 dark:text-gray-400">
      Showing {resultCount} of {totalCount} applications
    </span>
  </div>
</div>

// vue-ui/src/components/FilterBar.vue
<script setup lang="ts">
import { computed } from 'vue';
import { XMarkIcon, FunnelIcon } from '@heroicons/vue/24/outline';
import type { FilterState, CompanyCategory, JobSource } from '@/types';
import { APPLICATION_STATUSES, COMPANY_CATEGORIES, JOB_SOURCES } from '@/types';

const props = defineProps<{
  filters: FilterState;
  resultCount: number;
  totalCount: number;
}>();

const emit = defineEmits<{
  'update:filters': [filters: Partial<FilterState>];
  clearFilters: [];
}>();

const activeFilterCount = computed(() => {
  let count = 0;
  if (props.filters.status) count++;
  if (props.filters.companyCategory) count++;
  if (props.filters.jobSource) count++;
  if (props.filters.skillsMatchMin) count++;
  if (props.filters.includeArchived) count++;
  return count;
});

function updateFilter<K extends keyof FilterState>(key: K, value: FilterState[K]) {
  emit('update:filters', { [key]: value });
}

function handleStatusChange(event: Event) {
  const value = (event.target as HTMLSelectElement).value;
  updateFilter('status', value || undefined);
}

function handleCategoryChange(event: Event) {
  const value = (event.target as HTMLSelectElement).value as CompanyCategory | '';
  updateFilter('companyCategory', value || undefined);
}

function handleSourceChange(event: Event) {
  const value = (event.target as HTMLSelectElement).value as JobSource | '';
  updateFilter('jobSource', value || undefined);
}

function handleSkillsChange(event: Event) {
  const value = (event.target as HTMLSelectElement).value;
  updateFilter('skillsMatchMin', value ? parseInt(value, 10) : undefined);
}

function handleArchivedChange(event: Event) {
  const checked = (event.target as HTMLInputElement).checked;
  updateFilter('includeArchived', checked);
}

function handleSortByChange(event: Event) {
  const value = (event.target as HTMLSelectElement).value as FilterState['sortBy'];
  updateFilter('sortBy', value);
}

function handleSortDirChange() {
  updateFilter('sortDir', props.filters.sortDir === 'asc' ? 'desc' : 'asc');
}
</script>

<template>
  <div class="bg-white dark:bg-gray-800 rounded-lg shadow-sm border border-gray-200 dark:border-gray-700 p-4 mb-6">
    <div class="flex flex-wrap gap-4">
      <!-- Status Filter -->
      <div class="flex-1 min-w-[150px]">
        <label
          for="status-filter"
          class="label mb-1"
        >Status</label>
        <select
          id="status-filter"
          class="input"
          :value="filters.status || ''"
          @change="handleStatusChange"
        >
          <option value="">
            All Statuses
          </option>
          <option
            v-for="status in APPLICATION_STATUSES"
            :key="status.value"
            :value="status.value"
          >
            {{ status.label }}
          </option>
        </select>
      </div>

      <!-- Category Filter -->
      <div class="flex-1 min-w-[150px]">
        <label
          for="category-filter"
          class="label mb-1"
        >Category</label>
        <select
          id="category-filter"
          class="input"
          :value="filters.companyCategory || ''"
          @change="handleCategoryChange"
        >
          <option value="">
            All Categories
          </option>
          <option
            v-for="category in COMPANY_CATEGORIES"
            :key="category.value"
            :value="category.value"
          >
            {{ category.label }}
          </option>
        </select>
      </div>

      <!-- Source Filter -->
      <div class="flex-1 min-w-[150px]">
        <label
          for="source-filter"
          class="label mb-1"
        >Source</label>
        <select
          id="source-filter"
          class="input"
          :value="filters.jobSource || ''"
          @change="handleSourceChange"
        >
          <option value="">
            All Sources
          </option>
          <option
            v-for="source in JOB_SOURCES"
            :key="source.value"
            :value="source.value"
          >
            {{ source.label }}
          </option>
        </select>
      </div>

      <!-- Skills Match Filter -->
      <div class="flex-1 min-w-[150px]">
        <label
          for="skills-filter"
          class="label mb-1"
        >Min Skills Match</label>
        <select
          id="skills-filter"
          class="input"
          :value="filters.skillsMatchMin || ''"
          @change="handleSkillsChange"
        >
          <option value="">
            Any
          </option>
          <option value="2">
            2+ Stars
          </option>
          <option value="3">
            3+ Stars
          </option>
          <option value="4">
            4+ Stars
          </option>
          <option value="5">
            5 Stars
          </option>
        </select>
      </div>

      <!-- Sort -->
      <div class="flex-1 min-w-[180px]">
        <label
          for="sort-filter"
          class="label mb-1"
        >Sort By</label>
        <div class="flex">
          <select
            id="sort-filter"
            class="input rounded-r-none"
            :value="filters.sortBy"
            @change="handleSortByChange"
          >
            <option value="dateApplied">
              Date Applied
            </option>
            <option value="companyName">
              Company Name
            </option>
            <option value="updatedAt">
              Last Updated
            </option>
          </select>
          <button
            type="button"
            class="px-3 border border-l-0 border-gray-300 dark:border-gray-600 rounded-r-md bg-gray-50 dark:bg-gray-700 text-gray-500 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-600"
            @click="handleSortDirChange"
          >
            {{ filters.sortDir === 'asc' ? '↑' : '↓' }}
          </button>
        </div>
      </div>
    </div>

    <div class="flex flex-wrap items-center justify-between mt-4 pt-4 border-t border-gray-200 dark:border-gray-700">
      <div class="flex items-center space-x-4">
        <label class="flex items-center space-x-2 cursor-pointer">
          <input
            type="checkbox"
            :checked="filters.includeArchived"
            class="rounded border-gray-300 dark:border-gray-600 text-primary-600 focus:ring-primary-500"
            @change="handleArchivedChange"
          >
          <span class="text-sm text-gray-700 dark:text-gray-300">Include archived</span>
        </label>

        <button
          v-if="activeFilterCount > 0"
          type="button"
          class="text-sm text-primary-600 dark:text-primary-400 hover:text-primary-700 dark:hover:text-primary-300 flex items-center"
          @click="emit('clearFilters')"
        >
          <XMarkIcon class="h-4 w-4 mr-1" />
          Clear filters ({{ activeFilterCount }})
        </button>
      </div>

      <div class="text-sm text-gray-500 dark:text-gray-400 flex items-center">
        <FunnelIcon class="h-4 w-4 mr-1" />
        Showing {{ resultCount }} of {{ totalCount }} applications
      </div>
    </div>
  </div>
</template>
