// svelte-ui/src/lib/components/RatingDisplay.svelte
<script lang="ts">
  interface Props {
    value: number;
    max?: number;
    showNumeric?: boolean;
  }

  let { value, max = 5, showNumeric = false }: Props = $props();

  const stars = $derived(Array.from({ length: max }, (_, i) => i < value));
</script>

<div class="flex items-center gap-0.5">
  {#each stars as filled}
    <svg
      class="h-4 w-4 {filled ? 'text-yellow-400' : 'text-gray-300 dark:text-gray-600'}"
      fill="currentColor"
      viewBox="0 0 20 20"
    >
      <path
        d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"
      />
    </svg>
  {/each}
  {#if showNumeric}
    <span class="ml-1 text-sm text-gray-600 dark:text-gray-400">{value}/{max}</span>
  {/if}
</div>

// vue-ui/src/components/RatingDisplay.vue
<script setup lang="ts">
import { computed } from 'vue';
import { StarIcon } from '@heroicons/vue/24/solid';
import { StarIcon as StarOutlineIcon } from '@heroicons/vue/24/outline';

const props = defineProps<{
  value: number;
  max?: number;
  showNumeric?: boolean;
}>();

const maxStars = computed(() => props.max ?? 5);

const stars = computed(() => {
  const result = [];
  for (let i = 1; i <= maxStars.value; i++) {
    result.push({
      filled: i <= props.value,
      key: i,
    });
  }
  return result;
});
</script>

<template>
  <div class="flex items-center">
    <div class="flex">
      <template
        v-for="star in stars"
        :key="star.key"
      >
        <StarIcon
          v-if="star.filled"
          class="h-4 w-4 text-yellow-400"
        />
        <StarOutlineIcon
          v-else
          class="h-4 w-4 text-gray-300 dark:text-gray-600"
        />
      </template>
    </div>
    <span
      v-if="showNumeric"
      class="ml-1 text-sm text-gray-500 dark:text-gray-400"
    >
      {{ value }}/{{ maxStars }}
    </span>
  </div>
</template>
